# Generated by Django 6.0.3 on 2026-05-17 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('REJECTED', 'Rejeté')], default='PENDING', help_text='Statut de validation du vote', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='candidates.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['election'], name='votes_vote_electio_fca917_idx'), models.Index(fields=['candidate'], name='votes_vote_candida_fb054f_idx'), models.Index(fields=['voter'], name='votes_vote_voter_i_623a69_idx'), models.Index(fields=['status'], name='votes_vote_status_520b58_idx')],
                'constraints': [models.UniqueConstraint(fields=('election', 'voter'), name='unique_vote_per_user_per_election')],
            },
        ),
    ]
