"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a local .env file in development.
# In production (Render) environment variables are injected by the platform.
load_dotenv(BASE_DIR / ".env")

# --- Environment helpers -------------------------------------------------
def env_bool(key: str, default: bool = False) -> bool:
    v = os.environ.get(key)
    if v is None:
        return default
    return str(v).lower() in ("1", "true", "yes")

def env_list(key: str, default=None):
    raw = os.environ.get(key)
    if raw is None:
        return list(default) if default is not None else []
    return [p.strip() for p in raw.split(",") if p.strip()]

# Environment mode: 'production' for Render; default is 'development'
ENV = os.environ.get("ENV", os.environ.get("DJANGO_ENV", "development")).lower()
IS_PRODUCTION = ENV == "production"

# DEBUG: explicit via env or default (False in production)
DEBUG = env_bool("DEBUG", default=(not IS_PRODUCTION))
if IS_PRODUCTION and DEBUG:
    raise RuntimeError("DEBUG must be False in production")

# SECRET_KEY: required in production
DEV_SECRET_KEY = "django-insecure-local-development-key-change-me"
SECRET_KEY = os.environ.get("SECRET_KEY", DEV_SECRET_KEY if not IS_PRODUCTION else None)
if IS_PRODUCTION and not SECRET_KEY:
    raise RuntimeError("SECRET_KEY must be set in production environment")

# ALLOWED_HOSTS: must be explicit in production and must not include '*'
ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", default=([] if IS_PRODUCTION else ["*"]))
if IS_PRODUCTION:
    if not ALLOWED_HOSTS:
        raise RuntimeError("ALLOWED_HOSTS must be set in production environment")
    if any(h == "*" for h in ALLOWED_HOSTS):
        raise RuntimeError("ALLOWED_HOSTS must not contain '*' in production")

LANGUAGES = [
    ("fr", "Français"),
    ("en", "English"),
    ("ar", "العربية"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'citizens',
    'users',
    'elections',
    'votes',
    'candidates',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
     'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# CORS configuration: explicit list required in production
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS", default=["http://localhost:3000", "http://localhost:5173", "https://voting-repo-eta.vercel.app"]
)
if IS_PRODUCTION:
    # Disallow permissive CORS in production
    if env_bool("CORS_ALLOW_ALL_ORIGINS", default=False):
        raise RuntimeError("Do not enable CORS_ALLOW_ALL_ORIGINS in production. Set CORS_ALLOWED_ORIGINS explicitly.")
    if not CORS_ALLOWED_ORIGINS:
        raise RuntimeError("CORS_ALLOWED_ORIGINS must be set in production environment")

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database configuration
if IS_PRODUCTION:
    DATABASE_URL = os.environ.get("DATABASE_URL")
    if DATABASE_URL:
        try:
            import dj_database_url

            DATABASES = {"default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)}
        except Exception as exc:
            raise RuntimeError(
                "dj-database-url is required to parse DATABASE_URL. Install dj-database-url"
            ) from exc
    else:
        # Fall back to individual POSTGRES_* vars if DATABASE_URL not provided
        pg_name = os.environ.get("POSTGRES_DB")
        pg_user = os.environ.get("POSTGRES_USER")
        pg_password = os.environ.get("POSTGRES_PASSWORD")
        pg_host = os.environ.get("POSTGRES_HOST", "localhost")
        pg_port = os.environ.get("POSTGRES_PORT", "5432")
        if not (pg_name and pg_user and pg_password):
            raise RuntimeError("Postgres credentials must be set in production (DATABASE_URL or POSTGRES_*)")
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": pg_name,
                "USER": pg_user,
                "PASSWORD": pg_password,
                "HOST": pg_host,
                "PORT": pg_port,
            }
        }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fr"
TIME_ZONE = "Africa/Nouakchott"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
if IS_PRODUCTION:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Custom user model
AUTH_USER_MODEL = "users.User"

# REST framework + JWT
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

# JWT signing key: required in production, fallback to SECRET_KEY only in development
JWT_SIGNING_KEY = os.environ.get("JWT_SIGNING_KEY") or (SECRET_KEY if not IS_PRODUCTION else None)
if IS_PRODUCTION and not JWT_SIGNING_KEY:
    raise RuntimeError("JWT_SIGNING_KEY must be set in production environment")

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=90),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": JWT_SIGNING_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}

# Security settings for production
if IS_PRODUCTION:
    SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True)
    SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", default=True)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    # Honor X-Forwarded-Proto when behind proxies (Render sets this)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
else:
    SECURE_SSL_REDIRECT = False

# Ensure default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
