# Generated by Django 6.0.3 on 2026-04-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nni', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('wilaya', models.CharField(choices=[('Hodh Ech Chargui', 'Hodh Ech Chargui'), ('Hodh El Gharbi', 'Hodh El Gharbi'), ('Assaba', 'Assaba'), ('Gorgol', 'Gorgol'), ('Brakna', 'Brakna'), ('Trarza', 'Trarza'), ('Adrar', 'Adrar'), ('Dakhlet Nouadhibou', 'Dakhlet Nouadhibou'), ('Tagant', 'Tagant'), ('Guidimagha', 'Guidimagha'), ('Tiris Zemmour', 'Tiris Zemmour'), ('Inchiri', 'Inchiri'), ('Nouakchott Ouest', 'Nouakchott Ouest'), ('Nouakchott Nord', 'Nouakchott Nord'), ('Nouakchott Sud', 'Nouakchott Sud')], max_length=50)),
                ('is_eligible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Citizen record',
                'verbose_name_plural': 'Citizen records',
                'ordering': ['full_name'],
            },
        ),
    ]
