# Generated by Django 6.0.3 on 2026-04-06 14:09

from django.db import migrations


def seed_citizens(apps, schema_editor):
    CitizenRecord = apps.get_model("citizens", "CitizenRecord")
    citizens = [
        {
            "nni": "1000000001",
            "full_name": "Mohamed Ould Ahmed",
            "phone_number": "22220101001",
            "wilaya": "Nouakchott Ouest",
            "is_eligible": True,
        },
        {
            "nni": "1000000002",
            "full_name": "Fatimetou Mint Sidi",
            "phone_number": "22220101002",
            "wilaya": "Nouakchott Nord",
            "is_eligible": True,
        },
        {
            "nni": "1000000003",
            "full_name": "Cheikh Ould El Hacen",
            "phone_number": "22220101003",
            "wilaya": "Nouakchott Sud",
            "is_eligible": True,
        },
        {
            "nni": "1000000004",
            "full_name": "Mariam Mint Mohamed",
            "phone_number": "22220101004",
            "wilaya": "Trarza",
            "is_eligible": True,
        },
        {
            "nni": "1000000005",
            "full_name": "Ahmed Salem Ould Bouna",
            "phone_number": "22220101005",
            "wilaya": "Brakna",
            "is_eligible": True,
        },
        {
            "nni": "1000000006",
            "full_name": "Khadijetou Mint Yahya",
            "phone_number": "22220101006",
            "wilaya": "Gorgol",
            "is_eligible": True,
        },
        {
            "nni": "1000000007",
            "full_name": "Sidi Mohamed Ould Jiddou",
            "phone_number": "22220101007",
            "wilaya": "Adrar",
            "is_eligible": True,
        },
        {
            "nni": "1000000008",
            "full_name": "Aissata Mint El Moctar",
            "phone_number": "22220101008",
            "wilaya": "Hodh El Gharbi",
            "is_eligible": True,
        },
        {
            "nni": "1000000009",
            "full_name": "Moustapha Ould Mahmoud",
            "phone_number": "22220101009",
            "wilaya": "Dakhlet Nouadhibou",
            "is_eligible": True,
        },
        {
            "nni": "1000000010",
            "full_name": "Zeinabou Mint Amar",
            "phone_number": "22220101010",
            "wilaya": "Guidimagha",
            "is_eligible": True,
        },
    ]

    for citizen in citizens:
        CitizenRecord.objects.update_or_create(nni=citizen["nni"], defaults=citizen)


def unseed_citizens(apps, schema_editor):
    CitizenRecord = apps.get_model("citizens", "CitizenRecord")
    CitizenRecord.objects.filter(nni__in=[f"100000000{i}" for i in range(1, 10)] + ["1000000010"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_citizens, unseed_citizens),
    ]
