# Generated by Django 6.0.3 on 2026-04-29 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('citizens', '0002_seed_citizens'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nni', models.CharField(max_length=10, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('voter', 'Voter')], default='voter', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('wilaya', models.CharField(blank=True, choices=[('Hodh Ech Chargui', 'Hodh Ech Chargui'), ('Hodh El Gharbi', 'Hodh El Gharbi'), ('Assaba', 'Assaba'), ('Gorgol', 'Gorgol'), ('Brakna', 'Brakna'), ('Trarza', 'Trarza'), ('Adrar', 'Adrar'), ('Dakhlet Nouadhibou', 'Dakhlet Nouadhibou'), ('Tagant', 'Tagant'), ('Guidimagha', 'Guidimagha'), ('Tiris Zemmour', 'Tiris Zemmour'), ('Inchiri', 'Inchiri'), ('Nouakchott Ouest', 'Nouakchott Ouest'), ('Nouakchott Nord', 'Nouakchott Nord'), ('Nouakchott Sud', 'Nouakchott Sud')], max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_account', to='citizens.citizenrecord')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
