# Generated by Django 6.0.3 on 2026-05-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_eligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_eligible',
            field=models.BooleanField(default=True),
        ),
    ]
