# Generated by Django 6.0.3 on 2026-05-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_eligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
