# Generated by Django 6.0.3 on 2026-05-17 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(help_text='تاريخ ميلاد المترشح — مطلوب للتحقق من السن', null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = plus haut)")),
                ('is_active', models.BooleanField(default=True, help_text='Si False, le candidat est désactivé (ne peut pas recevoir de votes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='elections.party')),
            ],
            options={
                'ordering': ['-created_at', 'name'],
                'unique_together': {('election', 'name')},
            },
        ),
    ]
