# Generated by Django 6.0.3 on 2026-05-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(default='Mauritanian', help_text='جنسية المترشح — يجب أن تكون موريتانية', max_length=100),
        ),
    ]
